import { InputRule } from "prosemirror-inputrules";
import { NodeType, Node as ProsemirrorNode, Schema, DOMParser as ProsemirrorDOMParser } from "prosemirror-model";
import { MarkdownSerializerState } from "prosemirror-markdown";
// v4 import is Node specific, ensure it's correctly aliased or used if building for browser/node separately.
// For shared code, a universal UUID solution might be better if not already handled by build process.
import { v4 as uuidv4 } from "uuid";
import Node from "./Node";
import { TokenConfig } from "../lib/markdown/types";
import TaskItemView from "@app/editor/components/TaskItemView";

export default class TaskItemNode extends Node {
  // Associates this Prosemirror node type with its React component for rendering.
  public component = TaskItemView;

  get name() {
    return "task_item";
  }

  get schema() {
    return {
      attrs: {
        // Unique Global Identifier for the task, crucial for syncing with backend Task model.
        guid: { default: "" },
        // Checked state of the task (true for completed, false for open).
        checked: { default: false },
      },
      // Content can be any inline content (text, links, etc.).
      content: "inline*",
      // `defining: true` means that this node's content is "isolated" from its parent.
      // For example, if you try to join two list items, you can't join their content if they are defining.
      // It also affects things like `Node.textContent`.
      defining: true,
      // Makes the node draggable in the editor.
      draggable: true,
      parseDOM: [
        {
          // Parses our custom HTML representation: <li data-type="task_item" data-guid="..." data-checked="...">
          tag: `li[data-type="${this.name}"]`, // Use this.name for robustness
          getAttrs: (dom: HTMLElement) => { // Typecast to HTMLElement for broader compatibility
            const liElement = dom as HTMLLIElement;
            return {
              guid: liElement.dataset.guid,
              checked: liElement.dataset.checked === "true",
            };
          },
        },
        // Support for parsing GitHub Flavored Markdown (GFM) style checkboxes from HTML.
        // This often comes from pasting content from GitHub or other Markdown editors.
        // GFM task list items are typically `<li>` with class `task-list-item` and an `<input type="checkbox">`.
        {
          tag: "li.task-list-item",
          getAttrs: (dom: HTMLElement) => {
            const liElement = dom as HTMLLIElement;
            const checkbox = liElement.querySelector<HTMLInputElement>(
              "input[type=checkbox]"
            );
            return {
              // Generate a new guid if one doesn't exist. This is important because GFM tasks
              // don't have our custom GUID. The `parseMarkdown` rule for GFM will also do this.
              guid: liElement.dataset.guid || uuidv4(),
              checked: checkbox?.checked || false,
            };
          },
          // Higher priority to ensure this rule processes GFM `li.task-list-item`
          // before a more generic `li` rule (from ListItem node) might claim it.
          priority: 100,
        },
      ],
      // Defines how this Prosemirror node is rendered into the DOM.
      // This DOM structure is what `TaskItemView` (the React component) will manage or replace.
      toDOM: (node: ProsemirrorNode) => [
        "li",
        {
          "data-type": this.name,
          "data-guid": node.attrs.guid,
          "data-checked": node.attrs.checked.toString(),
          class: `task-list-item ${node.attrs.checked ? "checked" : ""}`,
        },
        [
          "span",
          {
            class: "checkbox",
            contentEditable: "false",
          },
          // The checkbox itself will be rendered by the React NodeView
        ],
        ["div", { class: "content" }, 0], // 0 indicates where content should be rendered
      ],
    };
  }

  // Serializes the task_item node back to our custom Markdown format.
  // Example: `[task:uuid-123] [x] Completed task text`
  toMarkdown(state: MarkdownSerializerState, node: ProsemirrorNode) {
    const checkbox = node.attrs.checked ? "[x]" : "[ ]";
    // Writes the custom task prefix, including GUID and checked state.
    state.write(`[task:${node.attrs.guid}] ${checkbox} `);
    // Renders the inline content (e.g., text, links) of the task item.
    state.renderInline(node);
  }

  // Defines how to parse this node from Markdown tokens generated by markdown-it.
  // This works in conjunction with the custom markdown-it plugin defined in `rulePlugins`.
  parseMarkdown(): TokenConfig {
    return {
      name: this.name, // Associates with this Prosemirror node type
      // This node type is created from `list_item` tokens.
      // The custom markdown-it plugin (in `rulePlugins`) is responsible for identifying
      // lines that represent tasks (either custom `[task:...]` or GFM `- [ ]`)
      // and modifying the standard `list_item` token to include task-specific metadata.
      token: "list_item",
      node: this.name, // Specifies that these tokens should create a `task_item` node.
      // `getAttrs` is crucial: it extracts attributes for the `task_item` node
      // from the markdown-it token.
      getAttrs: (tok: any) => { // `tok` is a markdown-it token
        // Case 1: Token comes from parsing GFM-style task: `- [ ] Task text`
        // The `markdown-it-task-lists` plugin (or similar, if used by Outline's base Markdown parser)
        // typically adds a `checked` boolean directly to the list_item token.
        // Our custom plugin in `rulePlugins` also handles GFM and adds `checked`.
        if (typeof tok.checked === "boolean") {
          return {
            checked: tok.checked,
            // `tok.taskGuid` would be set by our custom plugin if it parsed a `[task:...]` string
            // that was *inside* a GFM-like list item.
            // If `tok.taskGuid` is not present (pure GFM item), generate a new GUID.
            guid: tok.taskGuid || uuidv4(),
          };
        }
        // Case 2: Token comes from parsing our custom format: `[task:uuid] [x] Task text`
        // Our custom plugin in `rulePlugins` will have processed the `[task:...]` prefix
        // and put `taskGuid` and `taskChecked` into the token's `meta` attribute (or directly).
        // The `getAttrs` here assumes they are directly on the token, adjusted by the plugin.
        return {
          checked: tok.taskChecked, // Set by our custom markdown-it plugin
          guid: tok.taskGuid,       // Set by our custom markdown-it plugin
        };
      },
    };
  }

  // Defines input rules for automatically creating a task_item node when typing certain patterns.
  inputRules({ type, schema }: { type: NodeType; schema: Schema }) {
    return [
      new InputRule(
        /^\s*(\[ \])\s$/,
        (state, match, start, end) => {
          const { tr } = state;
          const guid = uuidv4();
          tr.replaceWith(
            start,
            end,
            type.create({ guid, checked: false })
          );
          return tr;
        }
      ),
    ];
  }

  /**
   * Provides markdown-it plugins for parsing tasks.
   * This plugin intercepts lines that look like tasks (either custom or GFM)
   * and modifies the token stream so that Prosemirror's `MarkdownParser` can
   * correctly create `task_item` nodes using the `parseMarkdown` spec above.
   */
  get rulePlugins(): Array<(md: any) => void> {
    return [
      // markdown-it plugin
      (md: any) => {
        // This rule attempts to identify task lines. It's a block rule.
        const taskItemRule = (state: any, silent: boolean) => {
          // `state` is markdown-it's state object.
          // `silent` is true if the parser is just checking if the rule matches.
          
          // Current line content
          const currentLine = state.src.slice(state.bMarks[state.line] + state.tShift[state.line], state.eMarks[state.line]);

          // Regex for our custom task format: e.g., `[task:GUID] [x] content`
          // Regex for GFM format: e.g., `- [ ] content` or `* [x] content`
          // Note: This simplified GFM regex assumes it's at the start of a list item line.
          // A more robust GFM task parsing is usually handled by `markdown-it-task-lists`
          // or similar, which this plugin might need to correctly interact with or replace.
          const customTaskRegex = /^\s*\[task:([0-9a-fA-F-]+)\]\s*\[( |x)\]\s*(.*)/;
          // GFM regex updated to handle common list markers and ensure it's at the start of a list item line content.
          // This regex expects that standard list parsing has already occurred or that this rule
          // is correctly interleaved. `markdown-it`'s list parsing is complex.
          // This rule focuses on identifying the "[ ]" or "[x]" part after list markers.
          const gfmTaskRegex = /^\s*(?:[-*+]|\d+\.)\s*\[( |x)\]\s+(.*)/; 

          let match;
          let isCustomFormat = false;
          let isGfmFormat = false;
          let taskContent = "";
          let taskGuid: string | undefined;
          let taskChecked = false;
          // `lineOffset` was intended to calculate the prefix length for `state.pos` adjustments.
          // However, for block rules modifying `state.line` is usually sufficient.
          // `state.pos` management is more critical for inline rules.

          // Try matching custom format first
          match = currentLine.match(customTaskRegex);
          if (match) {
            isCustomFormat = true;
            taskGuid = match[1];
            taskChecked = match[2].toLowerCase() === "x";
            taskContent = match[3];
          } else {
            // Try matching GFM format
            match = currentLine.match(gfmTaskRegex);
            if (match) {
              isGfmFormat = true;
              taskGuid = uuidv4(); // GFM tasks don't have inherent GUIDs, so generate one.
              taskChecked = match[1].toLowerCase() === "x";
              taskContent = match[2];
            }
          }

          if (!isCustomFormat && !isGfmFormat) {
            return false; // Not a task line according to our patterns.
          }

          if (silent) {
            // If silent, just report success if it matches.
            return true;
          }

          // --- Token manipulation for Prosemirror ---
          // The goal is to create a token stream that `task_item.parseMarkdown.getAttrs` can understand.
          // We make it look like a standard `list_item` but add our task metadata.
          
          // This block rule generates new tokens for the task item.
          // It effectively consumes the current line and tells markdown-it how to interpret it.
          
          let token;
          
          // 1. list_item_open: Signals the start of a list item.
          token = state.push('list_item_open', 'li', 1);
          // `markup` should be the list marker (e.g., '-', '*', '1.')
          // For custom tasks not explicitly in a list, we can default to '-'.
          // For GFM, `state.src[state.bMarks[state.line] + state.tShift[state.line]]` might give the marker.
          token.markup = isGfmFormat ? state.src[state.bMarks[state.line] + state.tShift[state.line]] : '-';
          
          // Add our custom attributes to the token's `meta` property.
          // `getAttrs` in `parseMarkdown` will use these.
          token.meta = token.meta || {};
          token.meta.task = true; // Signal that this is a task
          token.meta.taskGuid = taskGuid;
          token.meta.taskChecked = taskChecked;
          // For GFM tokens, some parsers (like markdown-it-task-lists) might set `checked` directly on the token.
          // Our `getAttrs` checks for `tok.checked` first, then `tok.meta.taskChecked`.
          // So, setting it on `meta` is primary for our logic. If also GFM, set `checked` for compatibility.
          if (isGfmFormat) {
            token.checked = taskChecked;
          }

          // 2. paragraph_open: Prosemirror's schema for `task_item` has `content: "inline*"`.
          // When parsing from Markdown, list item content (even if inline) is often wrapped in paragraph tokens.
          // Prosemirror's `MarkdownParser` typically expects this structure.
          // We mark this paragraph as "hidden" so it doesn't create an actual `paragraph` node in PM,
          // but rather its content is taken as the direct content of the `task_item`.
          token = state.push('paragraph_open', 'p', 1);
          token.hidden = true; 

          // 3. Inline content token (text): Contains the actual text of the task.
          token = state.push('text', '', 0);
          token.content = taskContent;
          // Note: If `taskContent` itself could contain Markdown (e.g., links, bold text),
          // then instead of a single 'text' token, we would need to call:
          // `state.md.inline.parse(taskContent, state.md, state.env, RDC_यहां_टोकन_डालें);`
          // and then push those generated inline tokens. For simplicity, this example assumes plain text.

          // 4. paragraph_close
          token = state.push('paragraph_close', 'p', -1);
          token.hidden = true;

          // 5. list_item_close: Signals the end of the list item.
          state.push('list_item_close', 'li', -1);
          
          // Advance the parser to the next line.
          state.line = state.line + 1; 
          // For block rules that consume the entire line(s), updating `state.line` is the standard way
          // to inform markdown-it that these lines have been processed.

          return true;
        };

        // Register the rule. It should run before markdown-it's default `list` rule
        // to allow it to identify and process task item lines. This ensures our more specific
        // task parsing takes precedence over generic list item parsing for these lines.
        // `alt` specifies other rule types this rule can be considered as, which helps markdown-it's
        // ruler to manage parsing order and fallbacks.
        md.block.ruler.before('list', 'outline_task_item', taskItemRule, {
          alt: [ 'paragraph', 'reference', 'blockquote', 'list' ]
        });
      },
    ];
  }
}
